# Generated by Django 5.2.13 on 2026-04-14 20:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('func', models.CharField(max_length=256, verbose_name='执行函数路径')),
                ('args', models.JSONField(blank=True, default=list, verbose_name='位置参数')),
                ('kwargs', models.JSONField(blank=True, default=dict, verbose_name='关键字参数')),
                ('schedule_type', models.CharField(choices=[('interval', '固定间隔'), ('cron', 'Cron 表达式')], max_length=20, verbose_name='调度类型')),
                ('cron_expression', models.CharField(blank=True, default='', help_text='schedule_type=cron 时必填，格式: 分 时 日 月 周', max_length=100, verbose_name='Cron 表达式')),
                ('interval_seconds', models.IntegerField(blank=True, help_text='schedule_type=interval 时必填', null=True, verbose_name='间隔秒数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '定时任务',
                'db_table': 'sys_cron_schedule',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='字典编码')),
                ('name', models.CharField(max_length=128, verbose_name='字典名称')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '字典类型',
                'db_table': 'sys_dict_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('ip', models.GenericIPAddressField(verbose_name='登录IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('success', models.BooleanField(verbose_name='是否成功')),
                ('reason', models.CharField(blank=True, default='', max_length=256, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '登录日志',
                'db_table': 'login_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=128, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='角色描述')),
                ('permissions', models.JSONField(default=list, verbose_name='权限列表')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 'auth_role',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='配置键')),
                ('value', models.TextField(default='', verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔'), ('json', 'JSON')], default='string', max_length=20, verbose_name='值类型')),
                ('group', models.CharField(blank=True, default='default', max_length=64, verbose_name='配置分组')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开(无需登录可读)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'db_table': 'sys_config',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('avatar', models.CharField(blank=True, default='', max_length=512, verbose_name='头像URL')),
                ('login_fail_count', models.IntegerField(default=0, verbose_name='连续登录失败次数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='密码最后修改时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='是否需要强制改密')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='app.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=512, verbose_name='请求路径')),
                ('query_params', models.TextField(blank=True, default='', verbose_name='查询参数')),
                ('ip', models.GenericIPAddressField(verbose_name='请求IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('status_code', models.IntegerField(default=0, verbose_name='响应状态码')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=256, verbose_name='密码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '密码历史',
                'db_table': 'auth_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='显示标签')),
                ('value', models.CharField(max_length=256, verbose_name='数据值')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.dicttype', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典数据',
                'db_table': 'sys_dict_data',
                'ordering': ['dict_type', 'sort', 'id'],
                'unique_together': {('dict_type', 'value')},
            },
        ),
    ]
